# ワークフロー名
name: PHPUnit test

# 対象のイベント
on:
  # push:
  pull_request:

jobs:
  #　ジョブ名
  phpunit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
        composer install

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libonig-dev libzip-dev unzip libxml2 zlib1g-dev

    - name: Run PHPUnit Test
      run: |
        vendor/bin/phpunit tests/HolidaysTest.php